#! /bin/bash
#Author	: Anonymous
#Date	:02-Feb-2020
echo ---------------------------------------------------------------------------------------------------------
python3 /home/shree/Documents/Python_Development/0_Python_Basic_Facts.py
echo ---------------------------------------------------------------------------------------------------------
python2 /home/shree/Documents/Python_Development/1_First_Program.py
echo ---------------------------------------------------------------------------------------------------------
python3 /home/shree/Documents/Python_Development/2_P2VSP3.py
echo ---------------------------------------------------------------------------------------------------------
python3 /home/shree/Documents/Python_Development/3_SimpleAdditionCode.py
echo ---------------------------------------------------------------------------------------------------------
python3 /home/shree/Documents/Python_Development/4_Python_Variables.py
echo ---------------------------------------------------------------------------------------------------------
python3 /home/shree/Documents/Python_Development/5_Sum_of_digits.py
echo ---------------------------------------------------------------------------------------------------------
python3 /home/shree/Documents/Python_Development/6_Defining_variables.py
echo ---------------------------------------------------------------------------------------------------------
python3 /home/shree/Documents/Python_Development/7_Strings_Demo.py
echo ---------------------------------------------------------------------------------------------------------
